name: Run DNS update
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover
      - name: DNS update
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
          set -e
          sed -i -e 's/API_KEY/${{ secrets.GANDI_API_KEY }}/' dns_records.yaml
          ./gandi_dns_plugin.py -f dns_records.yaml | tee /tmp/response.yaml
          grep -q 'output_id: success' /tmp/response.yaml && rc=$? || rc=$?
          rm -rf /tmp/response.yaml
          exit $rc
